/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Validation.h"


void
validationbut_1(char *host)
{
	CLIENT *clnt;
	reponse  *result_1;
	data  validation_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ValidationBut, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = validation_1(&validation_1_arg, clnt);
	if (result_1 == (reponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	printf("Resultat: %d\n", result_1->ok);
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	validationbut_1 (host);
exit (0);
}
