/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VALIDATION_H_RPCGEN
#define _VALIDATION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char cleBallon[32];
	char RFID[32];
};
typedef struct data data;


struct reponse {
	int ok;
};
typedef struct reponse reponse;


#define ValidationBut 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define Validation 1
extern  reponse * validation_1(data *, CLIENT *);
extern  reponse * validation_1_svc(data *, struct svc_req *);
extern int validationbut_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Validation 1
extern  reponse * validation_1();
extern  reponse * validation_1_svc();
extern int validationbut_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_reponse (XDR *, reponse*);
extern  bool_t xdr_reponse (XDR *, reponse*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_data ();
extern bool_t xdr_reponse ();
extern bool_t xdr_reponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VALIDATION_H_RPCGEN */
