/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Validation.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cleBallon, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->RFID, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reponse (XDR *xdrs, reponse *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ok))
		 return FALSE;
	return TRUE;
}
