/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Validation.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>



int validationbut_1(char *host, char *ballon){
	CLIENT *clnt;
	reponse  *result_1;
	data  validation_1_arg;

	#ifndef	DEBUG
		clnt = clnt_create (host, ValidationBut, VERSION_UN, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */
	printf("%s\n", ballon);
	strcpy(validation_1_arg.cleBallon, ballon);
	result_1 = validation_1(&validation_1_arg, clnt);
	if (result_1 == (reponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
	return result_1->ok;
}



/*int main (int argc, char *argv[]){

	
	printf("Resultat: %d\n", validationbut_1 ("localhost","3463456458032135435"));

	exit (0);

}*/
